# .github/actions/checkov-scan/action.yml

name: "Checkov Security Scan"
description: "Run Checkov security scans on infrastructure code"
inputs:
  directory:
    description: "Directory to scan"
    required: false
    default: "./infra"
  severity:
    description: "Severity level to fail the pipeline"
    required: false
    default: "high"
  output-file:
    description: "Output file for the Checkov report"
    required: false
    default: "checkov-report.json"
  continue-on-error:
    description: "Whether to continue on error"
    required: false
    default: "true"

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Checkov
      shell: bash
      run: |
        pip install checkov

    - name: Run Checkov on Infrastructure Code
      shell: bash
      run: |
        checkov -d ${{ inputs.directory }} \
          --framework terraform,kubernetes,cloudformation \
          --output json \
          --output-file ${{ inputs.output-file }} \
          --severity ${{ inputs.severity }}

    - name: Upload Checkov Report as Artifact
      uses: actions/upload-artifact@v3
      with:
        name: checkov-reports
        path: ${{ inputs.output-file }}
