name: Security Scans

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  semgrep:
    name: Semgrep Security Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Semgrep using pip
        run: |
          pip install semgrep

      - name: Semgrep Login (if necessary)
        run: |
          semgrep login --token ${{ secrets.SEMGREP_TOKEN }}

      - name: Run Semgrep Security Audit
        uses: returntocorp/semgrep-action@v1
        with:
          config: "p/security-audit"
          # auditOn: "error"

      - name: Run Semgrep Secrets Scan
        uses: returntocorp/semgrep-action@v1
        with:
          config: "p/secrets"
          # auditOn: "error"

      - name: Run Semgrep CI Scan
        uses: returntocorp/semgrep-action@v1
        with:
          config: "p/ci"
          # auditOn: "error"

  checkov:
    name: Checkov Security Scan
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Checkov
        run: |
          pip install checkov

      - name: Run Checkov on Infrastructure Code
        run: |
          checkov -d ./infra \
            --framework terraform,kubernetes,cloudformation \
            --output cli
