name: Security Scans

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  semgrep:
    name: Semgrep Security Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Semgrep using pip
        run: |
          pip install semgrep

      - name: Run Semgrep Security Audit
        env:
          SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_TOKEN }}
        run: |
          semgrep --config "p/security-audit"

      - name: Run Semgrep Secrets Scan
        env:
          SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_TOKEN }}
        run: |
          semgrep --config "p/secrets"

      - name: Run Semgrep CI Scan
        env:
          SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_TOKEN }}
        run: |
          semgrep --config "p/ci"

  checkov:
    name: Checkov Security Scan
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Checkov
        run: |
          pip install checkov

      - name: Run Checkov on Infrastructure Code
        run: |
          checkov -d ./infra \
            --framework terraform,kubernetes,cloudformation \
            --output cli
