name: Security Scans

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  checkov:
    name: Checkov Security Scan
    runs-on: ubuntu-latest
    steps:
      - name: Run Checkov Composite Action
        uses: ./.github/actions/checkov-scan
        with:
          directory: ./infra
          severity: high
          output-file: checkov-report.json
          continue-on-error: true
